# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core app to Azure Function App - quartile-function-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'src/Quartile.Functions' # set this to the path to your web app project, defaults to the repository root
  DOTNET_VERSION: '8.0.x' # set this to the dotnet version to use

jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: 'Resolve Project Dependencies Using Dotnet'
        shell: pwsh
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet build --configuration Release --output ./output
          popd
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0784403BA6224965AD71274F70D7469F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_05D6201DCCE741BD97645206F8DED005 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_58B0DEA01DE843DBB8BB9D33C6A3D67B }}

      - name: 'Deploy to Staging Slot'
        uses: Azure/functions-action@v1
        id: fa-staging
        with:
          app-name: 'quartile-function-prod'
          slot-name: 'staging'
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          
      - name: 'Configure Staging Slot Settings'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'quartile-function-prod'
          slot-name: 'staging'
          app-settings-json: |
            [
              {
                "name": "SqlConnectionString",
                "value": "${{ secrets.AZURE_SQL_CONNECTION_STRING }}",
                "slotSetting": false
              },
              {
                "name": "WEBSITE_AUTHENTICATION_ANONYMOUS",
                "value": "true",
                "slotSetting": false
              },
              {
                "name": "FUNCTIONS_WORKER_RUNTIME",
                "value": "dotnet-isolated",
                "slotSetting": false
              },
              {
                "name": "FUNCTIONS_EXTENSION_VERSION",
                "value": "~4",
                "slotSetting": false
              }
            ]
            
      - name: 'Wait for Staging to be ready'
        run: Start-Sleep -Seconds 30
          
      - name: 'Swap Staging to Production'
        run: az webapp deployment slot swap --name quartile-function-prod --resource-group quartile-grupo --slot staging --target-slot production
          