# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - quartile-api-prod

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: dotnet publish
        run: dotnet publish -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A951A2540BF24D0998DCAD951DCBECAB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1EC5E02EBDEB44A3A8784BFCB418D752 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_F04BFA288A8F4B39A7FC364751E3F6B0 }}

      - name: Deploy to Staging Slot
        id: deploy-to-staging
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'quartile-api-prod'
          slot-name: 'staging'
          package: .
          
      - name: Configure Staging Slot Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: 'quartile-api-prod'
          slot-name: 'staging'
          app-settings-json: |
            [
              {
                "name": "ConnectionStrings__QuartileConnection",
                "value": "${{ secrets.AZURE_SQL_CONNECTION_STRING }}",
                "slotSetting": false
              }
            ]
            
      - name: Wait for Staging to be ready
        run: Start-Sleep -Seconds 30
          
      - name: Swap Staging to Production
        run: az webapp deployment slot swap --name quartile-api-prod --resource-group quartile-grupo --slot staging --target-slot production
          